export const availableCards = [
    { name: 'Rufy', hp: 230, haki: 'Conquistatore', specialMove: { name: 'Gomu Gomu no Pistol', damage: 55 }, preferredIsland: 'Wano', fruitType: 'Paramisha', background: "url('./assets/char/Gomu_Gomu_no_Pistol.png')" },
    { name: 'Zoro', hp: 240, haki: 'Osservazione', specialMove: { name: 'Santoryu', damage: 60 }, preferredIsland: 'Wano', fruitType: 'Normale', background: "url('./assets/char/OcKaS4JH73GDNC28LtgRDfbWyr65ptJlBkY4TBQh.jpg')" },
    { name: 'Nami', hp: 180, haki: 'Armatura', specialMove: { name: 'Clima-Tact', damage: 40 }, preferredIsland: 'Orange Town', fruitType: 'Normale', background: "url('./assets/char/Nuovo_sorcery_clima_takt.png')" },
    { name: 'Sanji', hp: 210, haki: 'Osservazione', specialMove: { name: 'Diable Jambe', damage: 45 }, preferredIsland: 'Baratie', fruitType: 'Normale', background: "url('./assets/char/diable-jambe-sanji-one-piece-poster-5.jpg')" },
    { name: 'Usopp', hp: 170, haki: 'Osservazione', specialMove: { name: 'Kabuto', damage: 35 }, preferredIsland: 'Enies Lobby', fruitType: 'Normale', background: "url('./assets/char/Ginga_Pachinko_Infobox.png')" },
    { name: 'Chopper', hp: 185, haki: 'Armatura', specialMove: { name: 'Rumble Ball', damage: 55 }, preferredIsland: 'Regno dei Ciliegi', fruitType: 'Zoan', background: "url('./assets/char/Rumble_Ball.png')" },
    { name: 'Robin', hp: 195, haki: 'Conquistatore', specialMove: { name: 'Cien Fleur', damage: 50 }, preferredIsland: 'Ohara', fruitType: 'Paramisha', background: "url('./assets/char/Cien_Fleur_Wing.png')" },
    { name: 'Franky', hp: 210, haki: 'Armatura', specialMove: { name: 'Franky Punch', damage: 65 }, preferredIsland: 'Water Seven', fruitType: 'Normale' },
    { name: 'Brook', hp: 180, haki: 'Osservazione', specialMove: { name: 'Soul Solid', damage: 40 }, preferredIsland: 'Thriller Bark', fruitType: 'Paramisha' },
    { name: 'Jinbe', hp: 230, haki: 'Armatura', specialMove: { name: 'Fish-Man Karate', damage: 70 }, preferredIsland: 'Isola degli Uomini-Pesce', fruitType: 'Normale' },
    { name: 'Ace', hp: 195, haki: 'Conquistatore', specialMove: { name: 'Hiken', damage: 65 }, preferredIsland: 'Marineford', fruitType: 'Rogia' },
    { name: 'Shanks', hp: 270, haki: 'Conquistatore', specialMove: { name: 'Conqueror’s Slash', damage: 80 }, preferredIsland: 'Marineford', fruitType: 'Normale' },
    { name: 'Big Mom', hp: 250, haki: 'Conquistatore', specialMove: { name: 'Prometheus Fire', damage: 70 }, preferredIsland: 'Whole Cake Island', fruitType: 'Paramisha' },
    { name: 'Kaido', hp: 290, haki: 'Conquistatore', specialMove: { name: 'Boro Breath', damage: 90 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Barbabianca', hp: 290, haki: 'Conquistatore', specialMove: { name: 'Quake Smash', damage: 80 }, preferredIsland: 'Marineford', fruitType: 'Paramisha' },
    { name: 'Sabo', hp: 225, haki: 'Armatura', specialMove: { name: 'Dragon Claw', damage: 65 }, preferredIsland: 'Dressrosa', fruitType: 'Rogia' },
    { name: 'Trafalgar Law', hp: 230, haki: 'Conquistatore', specialMove: { name: 'Shambles', damage: 65 }, preferredIsland: 'Dressrosa', fruitType: 'Paramisha' },
    { name: 'Boa Hancock', hp: 185, haki: 'Osservazione', specialMove: { name: 'Love Arrow', damage: 50 }, preferredIsland: 'Amazon Lily', fruitType: 'Paramisha' },
    { name: 'Mihawk', hp: 260, haki: 'Osservazione', specialMove: { name: 'Black Blade', damage: 75 }, preferredIsland: 'Baratie', fruitType: 'Normale' },
    { name: 'Doflamingo', hp: 235, haki: 'Conquistatore', specialMove: { name: 'Parasite Strings', damage: 65 }, preferredIsland: 'Dressrosa', fruitType: 'Paramisha' },
    { name: 'Eneru', hp: 200, haki: 'Osservazione', specialMove: { name: 'Raigo', damage: 70 }, preferredIsland: 'Skypea', fruitType: 'Rogia' },
    { name: 'Crocodile', hp: 200, haki: 'Armatura', specialMove: { name: 'Desert Spada', damage: 60 }, preferredIsland: 'Alabasta', fruitType: 'Rogia' },
    { name: 'Marco', hp: 240, haki: 'Armatura', specialMove: { name: 'Phoenix Brand', damage: 70 }, preferredIsland: 'Marineford', fruitType: 'Zoan' },
    { name: 'Katakuri', hp: 250, haki: 'Conquistatore', specialMove: { name: 'Mochi Thrust', damage: 70 }, preferredIsland: 'Whole Cake Island', fruitType: 'Paramisha' },
    { name: 'Barbanera', hp: 280, haki: 'Conquistatore', specialMove: { name: 'Darkness Swirl', damage: 85 }, preferredIsland: 'Marineford', fruitType: 'Rogia' },
    { name: 'Akainu', hp: 280, haki: 'Conquistatore', specialMove: { name: 'Magma Fist', damage: 85 }, preferredIsland: 'Marineford', fruitType: 'Rogia' },
    { name: 'Garp', hp: 270, haki: 'Conquistatore', specialMove: { name: 'Fist of Love', damage: 75 }, preferredIsland: 'Marineford', fruitType: 'Normale' },
    { name: 'Smoker', hp: 220, haki: 'Armatura', specialMove: { name: 'White Out', damage: 50 }, preferredIsland: 'Logue Town', fruitType: 'Rogia' },
    { name: 'Kizaru', hp: 260, haki: 'Osservazione', specialMove: { name: 'Light Speed Kick', damage: 65 }, preferredIsland: 'Arcipelago Sabaody', fruitType: 'Rogia' },
    { name: 'Aokiji', hp: 270, haki: 'Armatura', specialMove: { name: 'Ice Age', damage: 75 }, preferredIsland: 'Ohara', fruitType: 'Rogia' },
    { name: 'Fujitora', hp: 250, haki: 'Osservazione', specialMove: { name: 'Gravity Blade', damage: 70 }, preferredIsland: 'Dressrosa', fruitType: 'Normale' },
    { name: 'Sentomaru', hp: 220, haki: 'Armatura', specialMove: { name: 'Defensive Slam', damage: 60 }, preferredIsland: 'Marineford', fruitType: 'Normale' },
    { name: 'Sengoku', hp: 275, haki: 'Conquistatore', specialMove: { name: 'Golden Shockwave', damage: 75 }, preferredIsland: 'Marineford', fruitType: 'Zoan' },
    { name: 'Perona', hp: 200, haki: 'Armatura', specialMove: { name: 'Hollow Ghost', damage: 55 }, preferredIsland: 'Thriller Bark', fruitType: 'Paramisha' },
    { name: 'Shiryu', hp: 250, haki: 'Osservazione', specialMove: { name: 'Invisible Slash', damage: 70 }, preferredIsland: 'Impel Down', fruitType: 'Paramisha' },
    { name: 'King', hp: 275, haki: 'Osservazione', specialMove: { name: 'Imperial Fire', damage: 80 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Queen', hp: 270, haki: 'Armatura', specialMove: { name: 'Plague Bomb', damage: 75 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Jack', hp: 265, haki: 'Armatura', specialMove: { name: 'Mammoth Charge', damage: 75 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Orochi', hp: 195, haki: 'Armatura', specialMove: { name: 'Hydra Head Strike', damage: 40 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Bellamy', hp: 200, haki: 'Armatura', specialMove: { name: 'Spring Hopper', damage: 50 }, preferredIsland: 'Dressrosa', fruitType: 'Paramisha' },
    { name: 'Koala', hp: 190, haki: 'Osservazione', specialMove: { name: 'Fishman Martial Arts', damage: 45 }, preferredIsland: 'Dressrosa', fruitType: 'Normale' },
    { name: 'Yamato', hp: 250, haki: 'Conquistatore', specialMove: { name: 'Thunder Bagua', damage: 70 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Oden', hp: 270, haki: 'Conquistatore', specialMove: { name: 'Two Sword Style', damage: 75 }, preferredIsland: 'Wano', fruitType: 'Normale' },
    { name: 'Koby', hp: 190, haki: 'Armatura', specialMove: { name: 'Impact Wave', damage: 50 }, preferredIsland: 'Marineford', fruitType: 'Normale' },
    { name: 'Reiju', hp: 205, haki: 'Armatura', specialMove: { name: 'Poison Pink', damage: 55 }, preferredIsland: 'Whole Cake Island', fruitType: 'Normale' },
    { name: 'Carrot', hp: 195, haki: 'Armatura', specialMove: { name: 'Electro Claw', damage: 50 }, preferredIsland: 'Zou', fruitType: 'Normale' },
    { name: 'Kinemon', hp: 225, haki: 'Armatura', specialMove: { name: 'Flame Rend', damage: 60 }, preferredIsland: 'Wano', fruitType: 'Normale' },
    { name: 'Monet', hp: 200, haki: 'Armatura', specialMove: { name: 'Snow Shield', damage: 40 }, preferredIsland: 'Punk Hazard', fruitType: 'Rogia' },
    { name: 'Vergo', hp: 230, haki: 'Armatura', specialMove: { name: 'Bamboo Strike', damage: 50 }, preferredIsland: 'Punk Hazard', fruitType: 'Normale' },
    { name: 'Hody Jones', hp: 235, haki: 'Armatura', specialMove: { name: 'Shark Onslaught', damage: 60 }, preferredIsland: 'Isola degli Uomini-Pesce', fruitType: 'Normale' },
    { name: 'Shiki', hp: 275, haki: 'Conquistatore', specialMove: { name: 'Island Drop', damage: 75 }, preferredIsland: 'Marineford', fruitType: 'Paramisha' },
    { name: 'Zephyr', hp: 265, haki: 'Conquistatore', specialMove: { name: 'Smash Fist', damage: 75 }, preferredIsland: 'Marineford', fruitType: 'Normale' },
    { name: 'Rayleigh', hp: 270, haki: 'Conquistatore', specialMove: { name: 'Dark King Slash', damage: 75 }, preferredIsland: 'Arcipelago Sabaody', fruitType: 'Normale' },
    { name: 'Kuma', hp: 255, haki: 'Osservazione', specialMove: { name: 'Paw Shock', damage: 75 }, preferredIsland: 'Thriller Bark', fruitType: 'Paramisha' },
    { name: 'Perona', hp: 190, haki: 'Armatura', specialMove: { name: 'Negative Hollow', damage: 50 }, preferredIsland: 'Thriller Bark', fruitType: 'Paramisha' },
    { name: 'Hawkins', hp: 215, haki: 'Osservazione', specialMove: { name: 'Straw Doll Curse', damage: 65 }, preferredIsland: 'Wano', fruitType: 'Paramisha' },
    { name: 'Apoo', hp: 200, haki: 'Armatura', specialMove: { name: 'Music Shockwave', damage: 55 }, preferredIsland: 'Wano', fruitType: 'Paramisha' },
    { name: 'X-Drake', hp: 225, haki: 'Osservazione', specialMove: { name: 'Allosaurus Rampage', damage: 70 }, preferredIsland: 'Wano', fruitType: 'Zoan' },
    { name: 'Capone Bege', hp: 210, haki: 'Armatura', specialMove: { name: 'Big Father', damage: 65 }, preferredIsland: 'Whole Cake Island', fruitType: 'Paramisha' },
    { name: 'Kid', hp: 230, haki: 'Conquistatore', specialMove: { name: 'Punk Gibson', damage: 70 }, preferredIsland: 'Wano', fruitType: 'Paramisha' },
    { name: 'Killer', hp: 200, haki: 'Osservazione', specialMove: { name: 'Beheading Claw', damage: 60 }, preferredIsland: 'Wano', fruitType: 'Normale' },
    { name: 'Mr.1', hp: 205, haki: 'Armatura', specialMove: { name: 'Steel Slash', damage: 60 }, preferredIsland: 'Alabasta', fruitType: 'Paramisha' },
    { name: 'Mr.2 Bon Clay', hp: 195, haki: 'Armatura', specialMove: { name: 'Clone Kick', damage: 55 }, preferredIsland: 'Impel Down', fruitType: 'Paramisha' },
    { name: 'Buggy', hp: 185, haki: 'Conquistatore', specialMove: { name: 'Chop-Chop Barrage', damage: 45 }, preferredIsland: 'Orange Town', fruitType: 'Paramisha' },
    { name: 'Arlong', hp: 200, haki: 'Armatura', specialMove: { name: 'Shark Blade', damage: 60 }, preferredIsland: 'Arlong Park', fruitType: 'Normale' },
    { name: 'Ivankov', hp: 235, haki: 'Conquistatore', specialMove: { name: 'Death Wink', damage: 70 }, preferredIsland: 'Impel Down', fruitType: 'Paramisha' },
    { name: 'Cavendish', hp: 210, haki: 'Osservazione', specialMove: { name: 'Hakuba Slash', damage: 60 }, preferredIsland: 'Dressrosa', fruitType: 'Normale' },
    { name: 'Bartolomeo', hp: 210, haki: 'Armatura', specialMove: { name: 'Barrier Crash', damage: 65 }, preferredIsland: 'Dressrosa', fruitType: 'Paramisha' },
    { name: 'Pica', hp: 285, haki: 'Armatura', specialMove: { name: 'Stone Golem Strike', damage: 70 }, preferredIsland: 'Dressrosa', fruitType: 'Paramisha' },
    { name: 'Diamante', hp: 225, haki: 'Osservazione', specialMove: { name: 'Flag Flurry', damage: 65 }, preferredIsland: 'Dressrosa', fruitType: 'Paramisha' },
    { name: 'Don Krieg', hp: 195, haki: 'Armatura', specialMove: { name: 'Explosive Lance', damage: 50 }, preferredIsland: 'Baratie', fruitType: 'Normale' },
    { name: 'Magellan', hp: 260, haki: 'Armatura', specialMove: { name: 'Venom Demon', damage: 75 }, preferredIsland: 'Impel Down', fruitType: 'Paramisha' },
    { name: 'Hannyabal', hp: 205, haki: 'Armatura', specialMove: { name: 'Flaming Halberd', damage: 50 }, preferredIsland: 'Impel Down', fruitType: 'Normale' },
    { name: 'Caesar Clown', hp: 220, haki: 'Armatura', specialMove: { name: 'Gastanet', damage: 60 }, preferredIsland: 'Punk Hazard', fruitType: 'Rogia' },
    { name: 'Gold D. Roger', hp: 250, haki: 'Conquistatore', specialMove: { name: 'Divine Slash', damage: 100 }, preferredIsland: 'Raftel', fruitType: 'Normale' }
];